Repository Neovici/cosmoz-image-viewer, pull requests merged in 2019-10, with the labels that each got.

#83 Fix Overlay -> Detached doesn't transition
  cosmoz-image-viewer-overlay.js
  cosmoz-image-viewer.js
  test/detach.html
Labels: enhancement

#86 chore: add github actions and semantic-release config
  .github/workflows/workflow.yml
  .travis.yml
  package-lock.json
  package.json
Labels: enhancement

#95 fix(ci): `npm version` hooks should be removed
  package.json
Labels: bug

#96 chore(ci): publish package publicly pretty please
  package.json
Labels: enhancement

#97 fix: github actions badge is missing
  README.md
Labels: enhancement

#98 chore(dev): enforce conventional commit messages
  .github/workflows/workflow.yml
  package-lock.json
  package.json
Labels: enhancement

#99 fix(deps): update dependencies
  package-lock.json
  package.json
Labels: dependencies, enhancement

#101 chore(ci): report coverage for master branch
  .github/workflows/workflow.yml
Labels: enhancement
